# docker-compose.app.yml
services:
  app:
    build: .
    container_name: sunrise-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_REMOTE_IP}:${DB_REMOTE_PORT}/${DB_REMOTE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_REMOTE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_REMOTE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_PROFILES_ACTIVE: docker-only-app
      BASE_URL: http://${IP_SERVER}:${PORT_SERVER}/app

      LOGGING_LEVEL_APP: INFO
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: WARN

      APP_MESSENGER_MAX_MESSAGE_SIZE: 5000

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8081:8080"