server:
  port: 8080

spring:
  config:
    activate:
      on-profile: "docker"

  application:
    name: Server

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/messenger_db}
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:defaultpass}
      driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.mail.ru
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform # ЭТО ДО ТЕХ ПОР, ПОКА 1 БАЗА ДАННЫХ
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    open-in-view: false

  # Автоматическое создание схемы
  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET:mysupersecretkeymysupersecretkeymysupersecretkey}

app:
  confirmation:
    base-url: ${BASE_URL}
  messenger:
    max-message-size: ${APP_MESSENGER_MAX_MESSAGE_SIZE:5000}
    allow-anonymous: ${APP_MESSENGER_ALLOW_ANONYMOUS:false}

logging:
  level:
    com.Sunrise: ${LOGGING_LEVEL_APP:INFO}
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: WARN