# application.yml
server:
  port: 8081

spring:

  config:
    activate:
      on-profile: docker-all-stack, docker-only-app, local

  application:
    name: Server

  datasource:
    url: ${SPRING_DATASOURCE_URL:${SPRING_DATASOURCE_REMOTE_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_REMOTE_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_REMOTE_PASSWORD}}
    driver-class-name: org.postgresql.Driver

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  mail:
    host: smtp.mail.ru
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: ${SPRING_HIBERNATE_FORMAT_SQL:false}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform # ЭТО ДО ТЕХ ПОР, ПОКА 1 БАЗА ДАННЫХ
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    open-in-view: false

  # Автоматическое создание схемы
  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET:mysupersecretkeymysupersecretkeymysupersecretkey}

app:
  confirmation:
    base-url: ${SPRING_BASE_URL:${BASE_URL}}
  messenger:
    max-message-size: ${APP_MESSENGER_MAX_MESSAGE_SIZE:5000}

logging:
  level:
    com.Sunrise: ${LOGGING_LEVEL_APP:INFO}
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: WARN